apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: postgresql-export
spec:
  type: Scala
  mode: cluster
  image: rayyildiz/pgexport
  imagePullPolicy: IfNotPresent
  mainClass: dev.rayyildiz.pgexp.ExportData
  mainApplicationFile: "local:///opt/spark/work/pg-exporter.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "tmp-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
    env:
      - name: PG_DATABASE
        value: "localhost"
      - name: PG_PORT
        value: "5432"
      - name: PG_USERNAME
        value: "postgres"
      - name: PG_PASSWORD
        value: "postgres"
      - name: PG_DBNAME
        value: "postgres"
      - name: EXPORT_PATH
        value: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
    env:
      - name: PG_DATABASE
        value: "localhost"
      - name: PG_PORT
        value: "5432"
      - name: PG_USERNAME
        value: "postgres"
      - name: PG_PASSWORD
        value: "postgres"
      - name: PG_DBNAME
        value: "postgres"
      - name: EXPORT_PATH
        value: "/tmp"
