apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: postgresql-export
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: rayyildiz/pgexport
#  imagePullPolicy: Always
  imagePullPolicy: IfNotPresent
  mainClass: dev.rayyildiz.pgexp.ExportData
  mainApplicationFile: "local:///opt/spark/work-dir/pg-exporter.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "tmp-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
    envVars:
      PG_DATABASE: "192.168.1.6"
      PG_PORT: "5432"
      PG_USERNAME: "postgres"
      PG_PASSWORD: "cds62hs16173cu3gvbaqtGa"
      PG_DBNAME: "postgres"
      EXPORT_PATH: "wasbs://data@symantodata.blob.core.windows.net/dev/messages"
      AZ_ACCOUNT_NAME: "symantodata"
      AZ_ACCOUNT_KEY: "FZvCellNzeQBvXrgfHIEQhpVD6xNN6WDDpDTbBBR5JtpgKXsiZe8EhFXwb3/WH/oALAtA9Pr+odS/q3azyznFw=="
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
    envVars:
      PG_DATABASE: "192.168.1.6"
      PG_PORT: "5432"
      PG_USERNAME: "postgres"
      PG_PASSWORD: "cds62hs16173cu3gvbaqtGa"
      PG_DBNAME: "postgres"
      EXPORT_PATH: "wasbs://data@symantodata.blob.core.windows.net/dev/messages"
      AZ_ACCOUNT_NAME: "symantodata"
      AZ_ACCOUNT_KEY: "FZvCellNzeQBvXrgfHIEQhpVD6xNN6WDDpDTbBBR5JtpgKXsiZe8EhFXwb3/WH/oALAtA9Pr+odS/q3azyznFw=="
